FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-python:3.7
LABEL maintainer="Dawn Ho <dawn.ho@gmail.com>"

RUN apt-get update && apt-get upgrade \
RUN apt-get install -yq \
  build-essential \
  python3-serial && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ./requirements.txt /requirements.txt

RUN pip3.7 install -r /requirements.txt

COPY . ./

ENV INITSYSTEM on

CMD ["bash", "setup-uart.sh"]
